### PR TITLE
added dash documentation support

### PR DESCRIPTION
**Pull request by bunnylushington**
Hi (and happy Thanksgiving!) -- 

I'm offering this PR as a replacement for PR #126.  In addition to the additional markup in the doc/markdown/*md files there's an escript capable of generating the Nitrogen.docset with the command `make dash-docs`.  The resulting `doc/dash/Nitrogen.tgz` file is appropriate for inclusion in the Dash-User-Contributions repository.

I have a [fork of Dash-User-Contributions](https://github.com/bunnylushington/Dash-User-Contributions/tree/master/docsets/Nitrogen) prepared for a PR; however:

* I don't think it's appropriate to submit the PR without your approval.

* If you'd rather ownership, I'm more than happy to cede responsibility!

In examining the existing .md files I found a couple of minor errors (a formatting error or two, a missing anchor tag, unqualified references to demos) that I corrected as part of this work.  I also added a blank line between 

```
## Section Name
* List Item
```

because pandoc was expecting one. I don't think this changes existing HTML generation.

### CODE REVIEW

**Comment by choptastic** [comment]
Hey @bunnylushington, this looks great!

I'm running into some issues here, and hopefully you can guide me.

I've added sqlite3, and installed docker, but it appears I'm missing something, as I'm getting a pile of errors that look like this:

```
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock ...
```
Seeing the "permission denied",  I tried running it with `sudo`, which seemed to work, though forcing a user to compile with `sudo` seems overkill to me.

Am I missing something?  Any thoughts?  I'm running this from ubuntu, so it may be a non-issue for you with OSX, but I figured it's worth seeing if it can be rectified.

**Comment by bunnylushington** [comment]
Hey Jesse -- 

You'll want to add your user to the docker group, something like

```
sudo usermod -aG docker $USER
newgrp docker
```

You're right that you don't really want to be generating the docs as root, that'll mess up your source tree for sure (for instance, running `git clean` won't work nicely).  Note that the container is actually [run as your user](https://github.com/bunnylushington/nitrogen_core/blob/c917533dc336ff17bd84d9048a720ffcc3da979a/doc/dash/md2docset#L239) but the owner:group of the socket is root:docker and you need to access that to talk to the docker daemon.  

If the inclusion of docker is a headache let me know; I'm happy to look first for a locally installed pandoc and use that if it's available and fall back on docker if not.

**Comment by choptastic** [comment]
Thank you for the clarification.  That was it.  I don't think it's a big deal - it doesn't have to be *super* user-friendly, since very few will build their own docsets, but it needs to be accessible enough that *I'll* remember how to do it later on :)

As this now works, I'll merge it.  I'll likely make a few minor changes, mostly with the script to make it work.

Thanks so much for all the work to make this happen.  I've tested the docset in Zeal and Dash, and it seems to work well.  I think this will be a very valuable addition.

**Comment by choptastic** [comment]
Oh, and as for ownership, no need to mess with any of that. If you're willing, feel free to submit the docset to the official Dash repository. Otherwise, I can do it.

**Comment by bunnylushington** [comment]
RIght on!  Thanks for taking the time to work through all of this.  I have the code teed up and ready to create a PR for submission into the Dash repo.  I'll create that shortly.  (I'll also nudge the developer again to consider including "Action" and "Validator" as categories.)

**Pull request merged**
