### PR TITLE
Mermaid

### PR DESCRIPTION
**Pull request by joaohf**
This is a initial proposal about how to integrate mermaid.

I'm pretty sure that there is a way better to do that. Mainly without creating another javascript function (mermaid).

I guess that the best approach is to use the mermaid api. Like described here: https://mermaid-js.github.io/mermaid/#/usage?id=api-usage

TODO:

- [x] cleanup and aligned with Nitrogen best practices
- [x] add mermaid options
- [x] how to update the graph
- [ ] ~~add mermaid events (https://mermaid-js.github.io/mermaid/#/usage?id=binding-events)~~

Reference: https://github.com/nitrogen/nitrogen_core/issues/99

### CODE REVIEW

**Comment by choptastic** [comment]
Hey @joaohf , this is really great so far!  I can't tell you how much I appreciate you taking the initiative on this!

On quick code review, I would say you've done a great job adopting the Nitrogen best practices.  I literally have no suggestions for code quality.

Obviously, encoding some common options would be a great next step.

For updating, I'd overload `wf:set` to update the graph ( the same way `wf:set` changes behavior based on the target element type (if it's an image, it changes the image URL, if it's form element, it updates the value).

The definition of `wf:set` is handled in https://github.com/nitrogen/nitrogen_core/blob/master/www/nitrogen.js#L991-L1001

Based on your code, you should be able to add an `else if($(el).hasClass('mermaid')) { ... }` to take care of it.

That said, I might be inclined to change the `mermaid` class you've specified in https://github.com/nitrogen/nitrogen_core/pull/123/files#diff-ae7fd4075818d11a9fd75ec04d9b9f79R44 to avoid possible name clashes if someone happens to actually make a normal element and give it a `mermaid` class (maybe someone making a game or something).

I'd probably do something like `wf_mermaid` or `nitrogen_mermaid`, which would almost certainly avoid conflicts.

But so far, this is great, and I love that you added a demo page!

**Comment by joaohf** [comment]
Thank you @choptastic for the support!! I really appreciate that.

I'm addressing your comments.

**Comment by joaohf** [comment]
Hello,

I've just added mermaid org file. But I can't run `make docs` properly. I got:

```
joaohf@porco:~/work/opensource/NitrogenProject.com/deps/nitrogen_core$ make docs
utils/make_docs/make_docs.el
Loading 00debian-vars...
Loading /etc/emacs/site-start.d/50asymptote.el (source)...
Loading /etc/emacs/site-start.d/50autoconf.el (source)...
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...
Loading /etc/emacs/site-start.d/50emacs-goodies-el.el (source)...
Loading /etc/emacs/site-start.d/50erlang-mode.el (source)...
Loading /etc/emacs/site-start.d/50texlive-lang-english.el (source)...
Loading erlang-skels...
Symbol’s function definition is void: org-publish-all
Makefile:19: recipe for target 'docs' failed
make: *** [docs] Error 255
```

**Comment by choptastic** [comment]
Thanks @joaohf! Don't worry about compiling the docs, that's always a little finnicky - I'll figure it out!

**Pull request merged**
